# config/schema.py
"""
Canonical complaint document template (SCHEMA).
Other modules should import SCHEMA and deepcopy it when creating a new doc.
"""

SCHEMA = {
    "department": "",
    "intent": "",              # e.g., "Water Supply", "GetStatus"
    "summary": "",             # short excerpt or autogenerated short summary
    "severity": "",
    "location": "",
    "name": "",
    "date": "",
    "language": "",            # detected language code, e.g. "hi", "en"
    "confidence_score": 0.0,
    "missing_fields": [],
    "final_summary": "",       # AI/NLG-generated confirmation sentence for user
    "raw_transcript": "",
    "translated_text": None
}
